version: "1.0"
info:
  model: int-scaffold
packages:
- name: Kvv_1302_prod960841Project
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: JMS2waySSL
  version: "1.0"
  gitServerName: kvv
  gitUrl: https://github.com/prabhakarsag
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: SIQAJDBCAdapterTests
  version: "1.0"
  gitServerName: kvv
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.kvv_1302_prod960841.integrations:jms_jndi_2waySSL
  packages:
  - name: Kvv_1302_prod960841Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.15
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: jms2wayssl_publisher:jms2wayssl_publisher
  packages:
  - name: JMS2waySSL
    version: "1.0"
- serviceName: pub.jms:send
  packages:
  - name: WmPublic
    version: 12.0.0.0.743
configurationVariables:
  jdbc.Embedded-Database-Pool.waitingThread: "0"
  jdbcfunc.ISDashboardStats.failFastMode: false
  jdbc.SAP-TxStore-Pool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/SAP-TxStore-Pool.log;ddtdbg.ProtocolTraceShowTime=true
  jdbc.Embedded-Database-Pool.spyenabled: "false"
  jdbcfunc.SAPTxStore.failFastMode: false
  jdbcfunc.Xref.failFastMode: true
  jdbc.SAP-TxStore-Pool.poolThreshold: "0"
  jdbc.SAP-TxStore-Pool.dbURL: jdbc:mysql://localhost:3306/SAPTRANSACTIONSTORE?useSSL=false&characterEncoding=utf-8&autoReconnect=true&maxReconnects=5&sessionVariables=wait_timeout=2147483
  jdbcfunc.ISDashboardStats.connPoolAlias: Embedded-Database-Pool
  jdbcfunc.Xref.connPoolAlias: Embedded-Database-Pool
  jdbc.Embedded-Database-Pool.userid: APP
  jdbcfunc.ISInternal.connPoolAlias: Embedded-Database-Pool
  jdbc.SAP-TxStore-Pool.expireTime: "60000"
  jdbc.Embedded-Database-Pool.password: "{AES}Zcw2EXTJgNDVmVzJO2Y3Bw=="
  jdbc.SAP-TxStore-Pool.spyparms: SpyAttributes=(log=(file)logs/spy/SAP-TxStore-Pool.log;logTName=yes;timestamp=yes)
  jdbc.SAP-TxStore-Pool.minConns: "5"
  jdbc.SAP-TxStore-Pool.userid: root
  jdbc.Embedded-Database-Pool.snoopenabled: "false"
  jdbc.SAP-TxStore-Pool.description: Connection Pool for the SAP Transaction Store
  jdbc.SAP-TxStore-Pool.snoopenabled: "false"
  jdbc.Embedded-Database-Pool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/Embedded-Database-Pool.log;ddtdbg.ProtocolTraceShowTime=true
  jdbc.SAP-TxStore-Pool.spyenabled: "false"
  jdbcfunc.ISInternal.failFastMode: true
  jdbc.Embedded-Database-Pool.maxConns: "10"
  jdbc.SAP-TxStore-Pool.waitingThread: "10"
  jdbc.SAP-TxStore-Pool.maxConns: "10"
  jdbc.Embedded-Database-Pool.expireTime: "60000"
  jdbc.Embedded-Database-Pool.poolThreshold: "0"
  jdbc.Embedded-Database-Pool.useSSL: "false"
  jdbc.SAP-TxStore-Pool.password: "{AES}nrGf3u7Wt20hFBGh5ZeEuQ=="
  jdbc.Embedded-Database-Pool.minConns: "0"
  jdbc.SAP-TxStore-Pool.driverAlias: MySQL CC Driver
  jdbc.Embedded-Database-Pool.driverAlias: Embedded Database Driver
  jdbc.Embedded-Database-Pool.spyparms: SpyAttributes=(log=(file)logs/spy/Embedded-Database-Pool.log;logTName=yes;timestamp=yes)
  jdbc.Embedded-Database-Pool.dbURL: jdbc:derby:embedded;create=true
  jdbc.SAP-TxStore-Pool.useSSL: "false"
  jdbcfunc.SAPTxStore.connPoolAlias: SAP-TxStore-Pool
